version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - goodevilgenius
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.0
    - 6.6.1
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: sqlite3
    versions:
    - 5.0.1
